"""Blood Risk Prediction API router — Module 2."""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from config import settings
from models.blood_model import load_model, predict_risk, train_and_save_model, FEATURE_NAMES

import os

router = APIRouter()

_model = None


def _get_model():
    global _model
    if _model is None:
        if not os.path.exists(settings.ML_MODEL_PATH):
            train_and_save_model(settings.ML_MODEL_PATH)
        _model = load_model(settings.ML_MODEL_PATH)
    return _model


class BloodParameters(BaseModel):
    wbc: float = Field(..., ge=0.5, le=30, description="White Blood Cell count (×10³/µL)")
    platelets: float = Field(..., ge=10, le=600, description="Platelet count (×10³/µL)")
    hemoglobin: float = Field(..., ge=5, le=20, description="Hemoglobin (g/dL)")
    ast: float = Field(..., ge=5, le=500, description="AST - Aspartate Aminotransferase (U/L)")
    alt: float = Field(..., ge=5, le=500, description="ALT - Alanine Aminotransferase (U/L)")
    crp: float = Field(..., ge=0, le=300, description="C-Reactive Protein (mg/L)")
    creatinine: float = Field(..., ge=0.3, le=10, description="Creatinine (mg/dL)")


class NormalRange(BaseModel):
    parameter: str
    unit: str
    normal_min: float
    normal_max: float
    user_value: float
    status: str


class BloodRiskResponse(BaseModel):
    prediction: str
    risk_level: int
    probabilities: dict[str, float]
    parameter_analysis: list[NormalRange]
    disclaimer: str


NORMAL_RANGES = {
    "wbc": {"unit": "×10³/µL", "min": 4.5, "max": 11.0},
    "platelets": {"unit": "×10³/µL", "min": 150, "max": 400},
    "hemoglobin": {"unit": "g/dL", "min": 12.0, "max": 17.0},
    "ast": {"unit": "U/L", "min": 10, "max": 40},
    "alt": {"unit": "U/L", "min": 7, "max": 56},
    "crp": {"unit": "mg/L", "min": 0, "max": 10},
    "creatinine": {"unit": "mg/dL", "min": 0.6, "max": 1.2},
}


@router.post("/predict", response_model=BloodRiskResponse)
async def predict_blood_risk(params: BloodParameters):
    """Analyze blood parameters and predict Nipah virus risk level."""
    try:
        model = _get_model()
    except Exception:
        raise HTTPException(status_code=503, detail="ML model is not available")

    result = predict_risk(model, params.model_dump())

    # Build parameter analysis
    analysis = []
    param_dict = params.model_dump()
    for name in FEATURE_NAMES:
        nr = NORMAL_RANGES[name]
        val = param_dict[name]
        if val < nr["min"]:
            status = "Low"
        elif val > nr["max"]:
            status = "High"
        else:
            status = "Normal"
        analysis.append(NormalRange(
            parameter=name.upper(),
            unit=nr["unit"],
            normal_min=nr["min"],
            normal_max=nr["max"],
            user_value=val,
            status=status,
        ))

    return BloodRiskResponse(
        prediction=result["prediction"],
        risk_level=result["risk_level"],
        probabilities=result["probabilities"],
        parameter_analysis=analysis,
        disclaimer=(
            "⚠️ DISCLAIMER: This prediction is generated by a machine learning model "
            "trained on synthetic data for educational and demonstration purposes only. "
            "It does NOT constitute a medical diagnosis. Always consult qualified "
            "healthcare professionals for medical interpretation of blood test results."
        ),
    )


@router.get("/parameters")
async def get_parameter_info():
    """Get information about accepted blood parameters and their normal ranges."""
    return {
        "parameters": [
            {
                "name": name,
                "unit": info["unit"],
                "normal_min": info["min"],
                "normal_max": info["max"],
                "description": f"{name.upper()} normal range: {info['min']}-{info['max']} {info['unit']}",
            }
            for name, info in NORMAL_RANGES.items()
        ]
    }
